version: '3'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin"

  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'planetscale/kubeconform']
    volumes:
      - ".:/plugin:ro"
