name: Kubeconform
description: Run kubeconform against kustomize-generated manifests
author: https://github.com/skottler
requirements:
  - docker
configuration:
  properties:
    files:
      type: string
    kustomize:
      type: boolean
  required:
    - files
  additionalProperties: false
