steps:
  - label: Shellcheck
    plugins:
      - shellcheck#v1.1.2:
          files:
            - hooks/*

  - label: "Lint :sparkles:"
    plugins:
      - plugin-linter#v2.0.0:
          id: planetscale/kubeconform

  - wait
  - label: Execute the plugin
    command: "echo 'run the plugin'"
    plugins:
      - "./../kubeconform-buildkite-plugin": ~
          path: config
          strict: true
