#!/bin/bash

set -euo pipefail

function plugin_read_list() {
  local prefix="BUILDKITE_PLUGIN_KUBECONFORM_$1"
  local parameter="${prefix}_0"

  if [[ -n "${!parameter:-}" ]]; then
    local i=0
    local parameter="${prefix}_${i}"
    while [[ -n "${!parameter:-}" ]]; do
      echo "${!parameter}"
      i=$((i+1))
      parameter="${prefix}_${i}"
    done
  elif [[ -n "${!prefix:-}" ]]; then
    echo "${!prefix}"
  fi
}

IFS=$'\n\t'
files=()

# Evaluate all the globs and return the files that exist
for file in $(plugin_read_list FILES) ; do
  if [[ -e $file ]] ; then
    files+=("$file")
  fi
done

if [[ -z ${files:-} ]] ; then
  echo "No files specified to run kubeconform against"
  exit 1
fi

BUILDKITE_PLUGIN_KUBECONFORM_VERSION="${BUILDKITE_PLUGIN_KUBECONFORM_VERSION:-master}"

echo "+++ Running kubeconform on ${#files[@]} files"

if docker run --rm -v "$PWD:/mnt" --workdir "/mnt" "ghcr.io/yannh/kubeconform:$BUILDKITE_PLUGIN_KUBECONFORM_VERSION" -skip ServiceMonitor,Kustomization "${files[@]}"; then
  echo "Kubeconform is ✅ on specified files"
else
  exit 1
fi
